### ISSUE TITLE
Unable to use the function map

### ISSUE THREAD

**Issue by rnagasam** [llathrop/AIND-Simulated_Annealing#1]
In `AIND-Simulated_Annealing.ipynb`, a variable is named `map`.

```
map = mpimg.read("map.png")
```

This is causing issues when I try to use the function `map` to solve the student questions (especially the `get_value()` method in the `TravellingSalesmanProblem` class. The error that is thrown is

```
TypeError: 'numpy.ndarray' object is not callable
```

While I can get around this by fixing the name in my local copy, please do change the variable name so that other students won't run into this issue. Thanks.

**Comment by llathrop** [comment]
your looking at my local version I worked for class, but you probably want the udacity version instead:
https://github.com/udacity/AIND-Simulated_Annealing

**Comment by rnagasam** [comment]
Sorry about that. I was in a hurry.

**Comment by llathrop** [comment]
:-)
